### ISSUE TITLE
Update README to have links point to right contribution guide, etc.

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/docs#265]
## 🧰 Task

The README refers to thinks in the napari/napari repo, for example Issues and the contribution guide.
These should be updated.
Additionally, I think it would be helpful to have the install and local make docs instructions as *brief* bullet points in the README for the advanced user to get going quickly.

**Comment by vreuter** [comment]
@psobolewskiPhD based on #366  feel free to assign me

**Comment by vreuter** [comment]
- [x] issues link(s) -- https://github.com/napari/docs/commit/26897eb90d4b4dc7d440eb9ce5f099b51992c49d
- [x] contributing guide link(s) -- https://github.com/napari/docs/commit/26897eb90d4b4dc7d440eb9ce5f099b51992c49d
- [ ] install bulleted summary -- https://github.com/napari/docs/pull/372
- [ ] local make docs bulleted summary -- https://github.com/napari/docs/pull/372
